# Generated by Django 2.0.8 on 2018-08-29 19:45

from django.db import migrations, models
import django.db.models.deletion
import quantity_field.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('concordance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='starpage',
            name='lead',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='starpage',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='starpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(template='blocks/rich_text_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('physical_characteristics', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('muted', 'Muted'), ('primary', 'Primary'), ('secondary', 'Secondary')]))])), ('orbital_characteristics', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('muted', 'Muted'), ('primary', 'Primary'), ('secondary', 'Secondary')]))]))]),
        ),
        migrations.AlterField(
            model_name='starpage',
            name='mass',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
    ]
