# Generated by Django 2.0.8 on 2018-08-29 21:37

from django.db import migrations, models
import django.db.models.deletion
import quantity_field.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('concordance', '0002_auto_20180829_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasPlanetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.TextField(blank=True)),
                ('lead', wagtail.core.fields.RichTextField(blank=True)),
                ('semi_major_axis', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('eccentricity', models.DecimalField(decimal_places=5, max_digits=5)),
                ('inclination', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('longitude_of_the_ascending_node', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('argument_of_periapsis', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('rotational_period', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('obliquity', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('precessional_period', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('mass', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('radius', quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=())),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(template='blocks/rich_text_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('orbital_characteristics', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('muted', 'Muted'), ('primary', 'Primary'), ('secondary', 'Secondary')]))]))])),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AlterField(
            model_name='starpage',
            name='mass',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
    ]
