# Generated by Django 2.0.8 on 2018-08-30 11:50

from django.db import migrations
import quantity_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concordance', '0004_auto_20180830_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasplanetpage',
            name='argument_of_periapsis',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='inclination',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='longitude_of_the_ascending_node',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='mass',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='obliquity',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='precessional_period',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='radius',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='rotational_period',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='gasplanetpage',
            name='semi_major_axis',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
        migrations.AlterField(
            model_name='starpage',
            name='mass',
            field=quantity_field.fields.MultiQuantityField(dim=1, max_length=255, units=()),
        ),
    ]
