# Generated by Django 2.0.8 on 2018-08-31 16:07

from django.db import migrations, models
import django.db.models.deletion
import quantity_field.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('pages', '0023_auto_20180619_1705'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailimages', '0020_add-verbose-name'),
        ('concordance', '0005_auto_20180830_1150'),
    ]

    operations = [
        migrations.RenameModel('GasPlanetPage', 'PlanetPage'),
    ]
